### ISSUE TITLE
xivparty, retail, unable to load 1.1.0 with March 18th commits

### ISSUE THREAD

**Issue by MahlKni** [tirem/XivParty#4]
Reverting the changes to status,statustracker, and statushelper.lua allowed it to load
![Error](https://user-images.githubusercontent.com/114670141/226691544-5c8b915e-df94-4404-a107-39adac1f1a2f.jpg)

**Comment by tirem** [comment]
It looks like you dont have the status submodule. Please download directly from the release panel on the right :) that has all submodules automatically included

**Comment by tirem** [comment]
Should be resolved in the most recent version!
